version: "3.9"
services:
  reading-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    image: reading-assistant
    container_name: reading-assistant
    env_file:
      - .env
    ports:
      - "3333:3000"
